### ISSUE TITLE
Kubernetes config for integration test

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#11]
This should setup and tear down a cluster
The output is a kops config
Separate Cluster created with its own state store so that you can create and delete this to make sure you  can have it work.

**Comment by burbel** [comment]
B-25974

**Comment by burbel** [comment]
Closing as a "duplicate" of the User Story that we are instead tracking in VersionOne - please use VersionOne for these items going forward (For EC2.7/EC2.8 at least).
