### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#12]
For new work we should be writing go tests and have some task for existing pieces.

**Comment by seizadi** [comment]
Get to 80% coverage

**Comment by burbel** [comment]
B-26542

**Comment by burbel** [comment]
Closing as a "duplicate" of the User Story that we are instead tracking in VersionOne - please use VersionOne for these items going forward (For EC2.7/EC2.8 at least).
