### ISSUE TITLE
Configure AWS access for kops

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#13]
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}  AWS_REGION=${AWS_REGION} AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} eval "$KOPS" update cluster --name "$NAME.$ZONE" -v 16 --lifecycle-overrides IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges

**Comment by seizadi** [comment]
@drewwells This issue is for AWS Flags from above cut and paste looks like we have requirements for only three flags AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION

I'll update the issue 8 which requires changing from "create cluster" to "update cluster" with the change to use  additional options in the script?
"$KOPS" update cluster --name "$NAME.$ZONE" -v 16 --lifecycle-overrides IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges"

https://github.com/infobloxopen/cluster-operator/issues/8

**Comment by seizadi** [comment]
@drewwells 
The above flags just resolved to just adding the lifecycle overrides, is this the only change needed?
I assume this can only be added when we switch to kops config and can specify the IAM Role/Policy.

--lifecycle-overrides IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges

**Comment by burbel** [comment]
All of these comments have been merged into B-25966, the "Operator container" VersionOne story.
