### ISSUE TITLE
use kops as go library

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#16]

**Comment by seizadi** [comment]
We have other issues to update exec.Cmd option. This issue is to investigate using vendoring.

**Comment by hryan-ib** [comment]
https://github.com/infobloxopen/cluster-operator/pull/27

**Comment by burbel** [comment]
Backwards but I am closing this issue as referenced/tracked in https://github.com/infobloxopen/cluster-operator/pull/27 (rather than open a specific VersionOne user story/task).
