### ISSUE TITLE
Make DeleteCluster so it can be called multiple errors

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#17]
Move items from seizadi issues to here.

**Comment by hryan-ib** [comment]
@seizadi could you elaborate on this? Not sure what the title means exactly.

**Comment by seizadi** [comment]
@hryan-ib 
DeleteCluster needs to be idempotent, i.e. when called multiple times it needs to be handle various states and recover. The current use case that we need to handle is when the cluster is for some reason already deleted. We need check if the cluster exists before we call 'delete cluster', we might find other states that need to be handled, but for now this is the only use case we know about.

To do this I would call 'get clusters -o json' and check if the cluster exists before calling 'delete cluster'
You can look at the code for SETUP state is has this pattern for checking the state of the cluster.

$ kops get clusters -o json
{"kind":"Cluster","apiVersion":"kops.k8s.io/v1alpha2","metadata":{"name":"seizadi.soheil.belamaric.com","creationTimestamp":"2020-03-14T23:17:27Z".....}

**Comment by hryan-ib** [comment]
https://github.com/infobloxopen/cluster-operator/pull/29

**Comment by hryan-ib** [comment]
D-01066

Closing as a "duplicate" of the User Story that we are instead tracking in VersionOne - please use VersionOne for these items going forward (For EC2.7/EC2.8 at least).
