### ISSUE TITLE
Infrastructure Operator to create VPC

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#18]

**Comment by drewwells** [comment]
kops can create VPCs. We should also support using an existing VPC

**Comment by seizadi** [comment]
Yes, VPCs should be a ConfigMap resource that is consumed. 
The ConfigMap name would be vpcCM and the key of interest would be vpcARN.

It can be an existing VPC or it could be produced by AWS Operator. If this value is not provided to the Cluster-Operator it will have Kops create a VPC on demand.

I started work on AWS Operator that can create VPCs using declarative pattern:
https://github.com/seizadi/aws-service-operator

It is still work in progress but it can use the CloudFormation we have in Cluster-Provisioning project.

**Comment by burbel** [comment]
This issue is now being tracked in VersionOne, under B-25970.  Currently assigned to Soheil.
