### ISSUE TITLE
operator container

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#20]
This falls out of CI and Integration tasks but I will track it here explicitly, combination of helm and CI to build container for cluster-operator.

I am going through and adding the items from seizadi repo.

**Comment by burbel** [comment]
B-25966

**Comment by burbel** [comment]
Closing as a "duplicate" of the User Story that we are instead tracking in VersionOne - please use VersionOne for these items going forward (For EC2.7/EC2.8 at least).
