### ISSUE TITLE
After Delete the Reconile loop get called again

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#23]
When update the finalizer in Status after delete this causes the control loop to be called (I think!) and since the resource is removed we generate an error, may be this is normal behavior but we generate error, look at if this could be cleaned up so we don't generate error, are there other cases where we need to generate error for this case?

2020-03-14T18:56:41.077-0700    INFO    controller_cluster      Reconciling Cluster     {"Request.Namespace": "seizadi", "Request.Name": "example-cluster"}
2020-03-14T18:56:41.077-0700    ERROR   controller_cluster      error requesting instance       {"Request.Namespace": "seizadi", "Request.Name": "example-cluster", "error": "Cluster.cluster-operator.infobloxopen.github.com \"example-cluster\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
        /Users/seizadi/projects/go-projects/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/infobloxopen/cluster-operator/pkg/controller/cluster.(*ReconcileCluster).Reconcile
        /Users/seizadi/projects/go-projects/src/github.com/infobloxopen/cluster-operator/pkg/controller/cluster/cluster_controller.go:88
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /Users/seizadi/projects/go-projects/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /Users/seizadi/projects/go-projects/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /Users/seizadi/projects/go-projects/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /Users/seizadi/projects/go-projects/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /Users/seizadi/projects/go-projects/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        /Users/seizadi/projects/go-projects/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88
2020-03-14T18:56:41.077-0700    DEBUG   controller-runtime.controller   Successfully Reconciled {"controller": "cluster-controller", "request": "seizadi/example-cluster"}

**Comment by burbel** [comment]
D-01065

**Comment by burbel** [comment]
Closing as a "duplicate" of the User Story that we are instead tracking in VersionOne - please use VersionOne for these items going forward (For EC2.7/EC2.8 at least).
