### ISSUE TITLE
Setup Operator Config 

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#24]
The operator-sdk uses viper for config subsystem, setup config and application flags for critical values that are imported from eventual configMap using environment variables. The current list that must be supported currently managed from Makefile for development:

export AWS_ACCESS_KEY_ID	 ?= $(shell aws configure get aws_access_key_id)
export AWS_SECRET_ACCESS_KEY ?= $(shell aws configure get aws_secret_access_key)
export AWS_REGION		     ?= $(shell aws configure get region)
export CLUSTER_OPERATOR_DEVELOPMENT ?= true
export KOPS_CLUSTER_DNS_ZONE ?= soheil.belamaric.com

**Comment by burbel** [comment]
B-25966

**Comment by burbel** [comment]
Closing as a "duplicate" of the User Story that we are instead tracking in VersionOne - please use VersionOne for these items going forward (For EC2.7/EC2.8 at least).
