### ISSUE TITLE
Add Cluster Operator Metrics

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#30]
There is support for Metrics in the Operator, define custom metrics:

   
   - Instrument Kops Phases:
      - Update
      - Validate
      - Delete
   - Operator Lifecycle
      - Reconcile

**Comment by burbel** [comment]
B-25965

**Comment by burbel** [comment]
Closing as a "duplicate" of the User Story that we are instead tracking in VersionOne - please use VersionOne for these items going forward (For EC2.7/EC2.8 at least).
