### ISSUE TITLE
use "kops update cluster" versus "kops create cluster" in the state machine

### ISSUE THREAD

**Issue by seizadi** [infobloxopen/cluster-operator#8]
Calling "update cluster" is idempotent, if cluster is not present it will create it and if it is already present it will update it. Allows us to stay in that state machine in case of errors and call kops again.

**Comment by seizadi** [comment]
When we call update use additional flags below as options....
$KOPS" update cluster --name "$NAME.$ZONE" -v 16 --lifecycle-overrides IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges

**Comment by seizadi** [comment]
One of the down side of using cluster update versus create is that there is not an option --vpc to use a shared VPC or for update. Also other options --master-count is no available. This wont be a problem when we migrate to using kops config, but for now it will be temporary limitation. This issue should be resolved when we migrate to support kops config option.

**Comment by drewwells** [comment]
Update uses a posted config. it reconciles state between kops state store and aws. Kops replace will post the config upserting changes from local to state store

**Comment by seizadi** [comment]
The code was integrated as part of the changes for kops config yaml pull request.
